import type { Metadata } from "next"
import { Fraunces, Hanken_Grotesk, JetBrains_Mono } from "next/font/google"
import "./globals.css"
import { PostHogProvider } from "./providers"
import { site } from "@/config/site"

const display = Fraunces({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-display",
  display: "swap",
})

const sans = Hanken_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-sans",
  display: "swap",
})

const mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
})

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} · ${site.title}`,
    template: `%s · ${site.name}`,
  },
  description: site.positioning,
  keywords: [
    site.name,
    "Full-Stack Developer",
    "Remote Software Developer",
    "React",
    "Next.js",
    "Node.js",
    "NestJS",
    "TypeScript",
    "GraphQL",
    "MongoDB Certified Associate Developer",
    "Remote developer UK US Australia",
  ],
  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  openGraph: {
    type: "website",
    url: site.url,
    siteName: site.name,
    title: `${site.name} · ${site.title}`,
    description: site.positioning,
    // Image supplied by app/opengraph-image.tsx (generated from config).
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} · ${site.title}`,
    description: site.positioning,
    creator: "@soft_eng_mamun",
    // Image supplied by app/twitter-image.tsx.
  },
  // Icons are generated by app/icon.tsx and app/apple-icon.tsx.
}

const personLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: site.name,
  jobTitle: site.title,
  url: site.url,
  email: `mailto:${site.email}`,
  address: { "@type": "PostalAddress", addressLocality: "Dhaka", addressCountry: "BD" },
  sameAs: [site.socials.github, site.socials.linkedin, site.socials.twitter],
  knowsAbout: ["TypeScript", "React", "Next.js", "Node.js", "NestJS", "GraphQL", "PostgreSQL", "MongoDB"],
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`dark ${display.variable} ${sans.variable} ${mono.variable}`}>
      <body className="font-sans antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personLd) }}
        />
        <PostHogProvider>{children}</PostHogProvider>
      </body>
    </html>
  )
}
