import type { Metadata } from "next"
import { Archivo, Bree_Serif, IBM_Plex_Mono } from "next/font/google"
import "./globals.css"
import { PostHogProvider } from "./providers"
import { ThemeProvider } from "@/components/theme/theme-provider"
import { DEFAULT_MODE, DEFAULT_PALETTE } from "@/config/palettes"
import { site } from "@/config/site"

/* Three roles, three faces.
   Bree Serif - display only, upright, restrained scale. Its rounded slabs are
   the warm note against the cold mineral palette.
   Archivo - running text. Condensed grotesk; dense technical prose sets tightly.
   IBM Plex Mono - data and labels. Tabular figures for the trace readouts. */
const display = Bree_Serif({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-display",
  display: "swap",
})

const body = Archivo({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-body",
  display: "swap",
})

const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
})

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} · ${site.title}`,
    template: `%s · ${site.name}`,
  },
  description: site.positioning,
  keywords: [
    site.name,
    "Full-Stack Developer",
    "Remote Software Developer",
    "React",
    "Next.js",
    "Node.js",
    "NestJS",
    "TypeScript",
    "GraphQL",
    "MongoDB Certified Associate Developer",
    "Remote developer UK US Australia",
  ],
  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  openGraph: {
    type: "website",
    url: site.url,
    siteName: site.name,
    title: `${site.name} · ${site.title}`,
    description: site.positioning,
    // Image supplied by app/opengraph-image.tsx (generated from config).
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} · ${site.title}`,
    description: site.positioning,
    creator: "@soft_eng_mamun",
    // Image supplied by app/twitter-image.tsx.
  },
  // Icons are generated by app/icon.tsx and app/apple-icon.tsx.
}

const personLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: site.name,
  jobTitle: site.title,
  url: site.url,
  email: `mailto:${site.email}`,
  address: { "@type": "PostalAddress", addressLocality: "Dhaka", addressCountry: "BD" },
  sameAs: [site.socials.github, site.socials.linkedin, site.socials.twitter],
  knowsAbout: ["TypeScript", "React", "Next.js", "Node.js", "NestJS", "GraphQL", "PostgreSQL", "MongoDB"],
}

/* Pre-paint theme resolution. Runs synchronously as the first thing in <body>,
   before React hydrates and before the browser paints, so there is no flash of
   the wrong palette and no hydration mismatch to repair.

   It is a raw string: no imports, no JSX, nothing that needs a bundle. The five
   palette ids and two modes are therefore inlined as literals - THEY MUST STAY
   IN SYNC WITH `PALETTES` / `MODES` in config/palettes.ts. Adding a palette
   there without adding it here means that palette can never be restored from
   localStorage (it silently falls back to graphite).

   Contract: an unknown/garbage/absent stored value falls back to the default
   and is never written to the DOM. localStorage access throws in some privacy
   modes, so the whole body is wrapped - if it throws, the attributes keep the
   server-rendered defaults below, which is the correct fallback. A throwing
   inline script here would abort before hydration, so this must never throw. */
const THEME_SCRIPT = `(function(){try{var P=["terracotta","verdigris","olive","aurora","ember","lagoon","orchid","slate"];var M=["dark","light"];var e=document.documentElement;var m=null,p=null;try{m=window.localStorage.getItem("mim-mode");p=window.localStorage.getItem("mim-palette")}catch(x){}e.setAttribute("data-mode",M.indexOf(m)>-1?m:"dark");e.setAttribute("data-palette",P.indexOf(p)>-1?p:"terracotta")}catch(x){}})();`

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      // Dark-by-default in the server markup, so the site is correct with JS
      // disabled. THEME_SCRIPT overwrites these before first paint when the
      // visitor has a stored preference.
      data-mode={DEFAULT_MODE}
      data-palette={DEFAULT_PALETTE}
      // THEME_SCRIPT mutates <html> before React hydrates.
      suppressHydrationWarning
      className={`${display.variable} ${body.variable} ${mono.variable}`}
    >
      <body className="font-sans antialiased">
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personLd) }}
        />
        <ThemeProvider>
          <PostHogProvider>{children}</PostHogProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
