import { ImageResponse } from "next/og"
import { site, coreStack } from "@/config/site"

// Dynamic social-share ("title") image, generated by the app from config/site.ts
// so it always reflects the current name, title, and stack. 1200×630.
// Applies to every route via the file convention; edit config, not a PNG.

export const alt = `${site.name} · ${site.title}`
export const size = { width: 1200, height: 630 }
export const contentType = "image/png"

const BG = "#100F0D"
const INK = "#ECE6D9"
const MUTED = "#9C9484"
const LINE = "#2A2620"
const ACCENT = "#FF6A2B"

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          position: "relative",
          height: "100%",
          width: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: BG,
          color: INK,
          padding: "72px 80px",
          fontFamily: "sans-serif",
        }}
      >
        {/* accent edge */}
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 8, background: ACCENT }} />

        {/* availability */}
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <div style={{ width: 14, height: 14, borderRadius: 999, background: ACCENT, display: "flex" }} />
          <div style={{ fontSize: 22, letterSpacing: 3, textTransform: "uppercase", color: MUTED }}>
            {site.availability}
          </div>
        </div>

        {/* name + title */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ fontSize: 92, fontWeight: 700, lineHeight: 1.02, letterSpacing: -2 }}>{site.name}</div>
          <div style={{ display: "flex", marginTop: 20, fontSize: 44, color: ACCENT }}>{site.title}</div>
          <div style={{ display: "flex", marginTop: 22, fontSize: 26, color: MUTED }}>
            Remote · UK, US &amp; Australia · {site.location} ({site.timezone})
          </div>
        </div>

        {/* stack */}
        <div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}>
          {coreStack.slice(0, 8).map((t) => (
            <div
              key={t}
              style={{
                display: "flex",
                border: `1px solid ${LINE}`,
                color: MUTED,
                borderRadius: 8,
                padding: "8px 16px",
                fontSize: 22,
              }}
            >
              {t}
            </div>
          ))}
        </div>
      </div>
    ),
    { ...size },
  )
}
